version: '3'

services:

  ### Management Servers ###

  ### DB Servers ###
  tenantdbserver:
    image: postgres:9.6
    volumes:
     - .data/tenantdb:/var/lib/postgresql/data
     - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    expose:
     - "5432"
    ports:
     - "5432:5432"
    networks:
     - microservicesnet
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: tenantdb
      ALLOW_IP_RANGE: 0.0.0.0/0
    command: -p 5432

  ### Microservices ###
  tenantservice:
    image: ghcr.io/jazzarran/tenant-service
    ports:
     - "8000:8000"
    networks:
     - microservicesnet
    environment:
      SPRING_PROFILES_ACTIVE: local

  administrationservice:
    image: ghcr.io/jazzarran/administration-service
    ports:
      - "8010:8010"
    networks:
      - microservicesnet
    environment:
      SPRING_PROFILES_ACTIVE: local

  ### Frontend Services ###

networks:
  microservicesnet:
