on: [workflow_dispatch]
name: Deploy PROD Infrastructure
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_PROD }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_PROD }}
        resourceGroupName: rg-HEALTH360-PROD
        template: ./solution/main.bicep
        parameters: ./solution/main.parameters.prod.json sshKey=${{ secrets.AZURE_VM_SSH_KEY_PROD }}
        failOnStdErr: false
