apiVersion: v1
kind: Pod
metadata:
  name: config-server
  labels:
    app: config-server
    type: core-service
spec:
  containers:
    - name: config-server
      image: geowest/config-server
      ports:
        - containerPort: 8888
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: configserver
spec:
  type: LoadBalancer
  ports:
  - port: 8888
    targetPort: 8888
  selector:
    app: config-server
---
apiVersion: v1
kind: Pod
metadata:
  name: discovery-server
  labels:
    app: discovery-server
    type: core-service
spec:
  containers:
    - name: discovery-server
      image: geowest/discovery-server
      ports:
        - containerPort: 8761
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: discoveryserver
spec:
  type: LoadBalancer
  ports:
  - port: 8761
    targetPort: 8761
  selector:
    app: discovery-server
---
apiVersion: v1
kind: Pod
metadata:
  name: router-server
  labels:
    app: router-server
    type: core-service
spec:
  containers:
    - name: router-server
      image: geowest/router-server
      ports:
        - containerPort: 5555
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: routerserver
spec:
  type: LoadBalancer
  ports:
  - port: 5555
    targetPort: 5555
  selector:
    app: router-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: organization-service-deployment
  labels:
    app: organization-service
    type: backend-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: organization-service
  template:
    metadata:
      labels:
        app: organization-service
    spec:
      containers:
      - name: organization-service
        image: geowest/organization-service
        args: ["--spring.profiles.active=dev"]
        ports:
        - containerPort: 8000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: organization-service
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: organization-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-service-deployment
  labels:
    app: vehicle-service
    type: backend-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vehicle-service
  template:
    metadata:
      labels:
        app: vehicle-service
    spec:
      containers:
      - name: vehicle-service
        image: geowest/vehicle-service
        args: ["--spring.profiles.active=dev"]
        ports:
        - containerPort: 8010
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: vehicle-service
spec:
  type: LoadBalancer
  ports:
  - port: 8010
    targetPort: 8010
  selector:
    app: vehicle-service
