name: Deploy to QA (Organization Service)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Enter reason for manual deployment'     
        required: true
  repository_dispatch:
  
jobs:
          
  deploy:
    name: Deploy Microservice
    runs-on: ubuntu-18.04
    environment: QA
    
    steps:
      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.AZURE_VM_IP_ADDRESS }}
          username: vmadminqa
          key: ${{secrets.AZURE_VM_SSH_PRIVATE_KEY}}
          port: 22
          script: |
            echo ${{ secrets.GIT_ACCESS_TOKEN }}
            docker login https://ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.GIT_PACKAGES_ACCESS_TOKEN }}
            docker pull ghcr.io/jazzarran/organization-service:latest
            
            docker container ls -al | grep organization-service-container && docker container stop organization-service-container 2> /dev/null || true
            docker container ls -al | grep organization-service-container && docker container kill organization-service-container 2> /dev/null || true
            docker container ls -al | grep organization-service-container && docker container rm organization-service-container 2> /dev/null || true
            docker run -d -p 8000:8000 \
                -e "SPRING_PROFILES_ACTIVE=qa" \
                -e "DB_HOST=health360-postgresdb-w1-qa.postgres.database.azure.com" \
                -e "DB_USERNAME=dbadmin@health360-postgresdb-w1-qa" \
                -e "DB_PASSWORD=Password!" \
                -t --name --restart unless-stopped organization-service-container ghcr.io/jazzarran/organization-service:latest
