on: [push,workflow_dispatch]
name: Deploy QA Infrastructure
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_QA }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_QA }}
        resourceGroupName: rg-HEALTH360-QA
        template: ./solution/main.bicep
        parameters: ./solution/main.parameters.qa.json adminSshKey="${{ secrets.AZURE_VM_SSH_PUBLIC_KEY_QA }}"
        failOnStdErr: false
