name: Deploy UAT Infrastructure.

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Enter environment deploying to'     
        required: true
      reason:
        description: 'Enter reason for manual deployment'     
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: UAT
    if: ${{ github.event.inputs.environment == 'UAT' }
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: rg-HEALTH360-UAT
        template: ./infrastructure/main.bicep
        parameters: ./infrastructure/main.parameters.uat.json adminSshKey="${{ secrets.AZURE_VM_SSH_PUBLIC_KEY }}"
        failOnStdErr: false
